package com.tallerexpress.repository.impl;
import com.tallerexpress.repository.ServiceOrderDao; import com.tallerexpress.model.*; import com.tallerexpress.config.Db; import java.sql.*; import java.util.*;
public class ServiceOrderDaoJdbc implements ServiceOrderDao {
 private ServiceOrder map(ResultSet r)throws SQLException{ServiceOrder o=new ServiceOrder();o.setId(r.getInt("id"));o.setClientId(r.getInt("client_id"));o.setVehicleId(r.getInt("vehicle_id"));o.setMechanicName(r.getString("mechanic_name"));o.setEntryDate(r.getTimestamp("entry_date").toLocalDateTime());o.setProblemDescription(r.getString("problem_description"));o.setDiagnosis(r.getString("diagnosis"));o.setStatus(OrderStatus.valueOf(r.getString("status")));o.setFinalCost(r.getBigDecimal("final_cost"));return o;}
 public int insertOrder(Connection c,ServiceOrder o)throws SQLException{String q="INSERT INTO service_orders(client_id,vehicle_id,mechanic_name,entry_date,problem_description,diagnosis,status,final_cost) VALUES(?,?,?,?,?,?,?,?) RETURNING id";try(PreparedStatement p=c.prepareStatement(q)){p.setInt(1,o.getClientId());p.setInt(2,o.getVehicleId());p.setString(3,o.getMechanicName());p.setTimestamp(4,Timestamp.valueOf(o.getEntryDate()));p.setString(5,o.getProblemDescription());p.setString(6,o.getDiagnosis());p.setString(7,o.getStatus().name());p.setBigDecimal(8,o.getFinalCost());try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}}
 public void insertPart(Connection c,int orderId,OrderPart x)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO order_parts(order_id,spare_part_id,quantity,unit_price) VALUES(?,?,?,?)")){p.setInt(1,orderId);p.setInt(2,x.sparePartId());p.setInt(3,x.quantity());p.setBigDecimal(4,x.unitPrice());p.executeUpdate();}}
 public void updateStatusAndCost(Connection c,int id,OrderStatus status,java.math.BigDecimal cost,String diagnosis)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE service_orders SET status=?,final_cost=?,diagnosis=? WHERE id=?")){p.setString(1,status.name());p.setBigDecimal(2,cost);p.setString(3,diagnosis);p.setInt(4,id);p.executeUpdate();}}
 public Optional<ServiceOrder> findById(int id)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM service_orders WHERE id=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())return Optional.empty();ServiceOrder o=map(r);o.setParts(findParts(id));return Optional.of(o);}}}
 public List<ServiceOrder> findByVehicle(int vehicleId)throws SQLException{List<ServiceOrder> l=new ArrayList<>();try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM service_orders WHERE vehicle_id=? ORDER BY entry_date DESC")){p.setInt(1,vehicleId);try(ResultSet r=p.executeQuery()){while(r.next()){ServiceOrder o=map(r);o.setParts(findPartsWith(c,o.getId()));l.add(o);}}}return l;}
 public List<OrderPart> findParts(int id)throws SQLException{try(Connection c=Db.getConnection()){return findPartsWith(c,id);}}
 private List<OrderPart> findPartsWith(Connection c,int id)throws SQLException{List<OrderPart> l=new ArrayList<>();String q="SELECT op.spare_part_id,sp.reference_code,sp.name,op.quantity,op.unit_price FROM order_parts op JOIN spare_parts sp ON sp.id=op.spare_part_id WHERE op.order_id=?";try(PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);try(ResultSet r=p.executeQuery()){while(r.next())l.add(new OrderPart(r.getInt(1),r.getString(2),r.getString(3),r.getInt(4),r.getBigDecimal(5)));}}return l;}
}
