package com.tallerexpress.repository.impl;
import com.tallerexpress.repository.UserDao; import com.tallerexpress.model.*; import com.tallerexpress.config.Db; import java.sql.*; import java.util.*;
public class UserDaoJdbc implements UserDao {
 private User map(ResultSet r)throws SQLException{return new User(r.getInt("id"),r.getString("username"),r.getString("password_hash"),r.getString("full_name"),Role.valueOf(r.getString("role")),UserStatus.valueOf(r.getString("status")),r.getTimestamp("created_at").toLocalDateTime());}
 public Optional<User> findByUsername(String u)throws SQLException{String q="SELECT * FROM users WHERE username=?";try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,u);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}}
 public Optional<User> findById(int id)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM users WHERE id=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}}
 public List<User> findAll()throws SQLException{List<User> l=new ArrayList<>();try(Connection c=Db.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT * FROM users ORDER BY id")){while(r.next())l.add(map(r));}return l;}
 public int insert(User u,Connection c)throws SQLException{String q="INSERT INTO users(username,password_hash,full_name,role,status,created_at) VALUES(?,?,?,?,?,?) RETURNING id";try(PreparedStatement p=c.prepareStatement(q)){p.setString(1,u.getUsername());p.setString(2,u.getPasswordHash());p.setString(3,u.getFullName());p.setString(4,u.getRole().name());p.setString(5,u.getStatus().name());p.setTimestamp(6,Timestamp.valueOf(u.getCreatedAt()));try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}}
 public void update(User u)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET full_name=?,role=?,status=? WHERE id=?")){p.setString(1,u.getFullName());p.setString(2,u.getRole().name());p.setString(3,u.getStatus().name());p.setInt(4,u.getId());p.executeUpdate();}}
 public void delete(int id)throws SQLException{try(Connection c=Db.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM users WHERE id=?")){p.setInt(1,id);p.executeUpdate();}}
}
